#define CATCH_CONFIG_MAIN
#include <catch.hpp>
#include <comments.hpp>
#include <double.hpp>
#include <identifier.hpp>
#include <integer.hpp>
#include <keywords.hpp>
#include <punctuation.hpp>
#include <string.hpp>
#include <whitespace.hpp>